// Mocks generated by Mockito 5.3.2 from annotations
// in restapi/test/users_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:flutter_finite_task/data/model//body_users.dart' as _i6;
import 'package:flutter_finite_task/data/model/menu_model.dart' as _i2;
import 'package:flutter_finite_task/data/model/users_response.dart' as _i3;
import 'package:flutter_finite_task/data/remote/users_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseMenu_0 extends _i1.SmartFake implements _i2.ResponseMenu {
  _FakeResponseMenu_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUsersResponse_1 extends _i1.SmartFake implements _i3.UsersResponse {
  _FakeUsersResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UsersService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsersService extends _i1.Mock implements _i4.UsersService {
  MockUsersService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ResponseMenu> fetchMenu() => (super.noSuchMethod(
        Invocation.method(
          #fetchMenu,
          [],
        ),
        returnValue: _i5.Future<_i2.ResponseMenu>.value(_FakeResponseMenu_0(
          this,
          Invocation.method(
            #fetchMenu,
            [],
          ),
        )),
      ) as _i5.Future<_i2.ResponseMenu>);
  @override
  _i5.Future<Map<String, dynamic>> listUsers() => (super.noSuchMethod(
        Invocation.method(
          #listUsers,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);
  @override
  _i5.Future<_i3.UsersResponse> fetchUsers() => (super.noSuchMethod(
        Invocation.method(
          #fetchUsers,
          [],
        ),
        returnValue: _i5.Future<_i3.UsersResponse>.value(_FakeUsersResponse_1(
          this,
          Invocation.method(
            #fetchUsers,
            [],
          ),
        )),
      ) as _i5.Future<_i3.UsersResponse>);
  @override
  _i5.Future<Map<String, dynamic>> createUsers(_i6.BodyUsers? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUsers,
          [user],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);
  @override
  _i5.Future<Map<String, dynamic>> editUsers(
    _i6.BodyUsers? user,
    int? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editUsers,
          [
            user,
            id,
          ],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);
  @override
  _i5.Future<Map<String, dynamic>> deleteUsers(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteUsers,
          [id],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);
}
